dev sealv4
ibarrond/Pyfhel pull request #141
Opened 2022-08-15 20:06 UTC by devharsh

- support for macOS
- SEALv4 upgrade with BGV scheme

2022-08-17 16:35 UTC, ibarrond requested changes

2022-08-17 16:35 UTC, ibarrond commented on Pyfhel/utils/cy_type_converters.pxi
> +        elif scheme.lower() in ('int', 'integer', 'bgv'):   scheme = "bgv"
Sadly we cannot have two schemes named 'int' or 'integer'. To keep backwards compatibility, I'd say we only allow BGV scheme to be referenced as 'bgv', leaving all integer-like references for BFV.

Change this line to `        elif scheme.lower() == 'bgv':   scheme = "bgv"`, and update comments related to it.

2022-08-17 16:35 UTC, ibarrond commented on Pyfhel/utils/cy_type_converters.pxi
> +                     ('int', 'integer', 'bgv') for bgv scheme,
Only 'bgv'

2022-08-17 16:35 UTC, ibarrond commented on Pyfhel/Pyfhel.pyx
> +            assert (sec>0 or q>0), "BFV scheme requires `sec` or `q` to be set."
BGV instead of BFV

2022-08-17 16:35 UTC, ibarrond commented on Pyfhel/PyPtxt.pyx
>          if (self._scheme != scheme_t.bfv):
scheme_t.bgv would raise this exception. change to have both conditions in one single `if` clause (`if a and b`)

2022-08-17 16:35 UTC, ibarrond commented on Pyfhel/PyPtxt.pyx
> +              * ('int', 'integer', int, 1, scheme_t.bgv) -> integer scheme.
Change to ` (3, scheme_t.bgv) -> integer scheme.`. We will leave BFV as default integer scheme.

2022-08-17 16:35 UTC, ibarrond commented on Pyfhel/PyCtxt.pyx
> +        elif self.scheme == Scheme_t.bgv:
Merge with previous `if` clause, since they do the same thing! (`if a or b`).

2022-08-17 16:35 UTC, ibarrond commented on Pyfhel/PyCtxt.pyx
> +        elif self.scheme==Scheme_t.bgv:
Merge with previous `if` clause, since they do the same thing! (`if a or b`).

2022-08-17 16:35 UTC, ibarrond commented on Pyfhel/PyCtxt.pyx
> +                * ('int', 'INTEGER', int, 1, Scheme_t.bgv) -> integer scheme.
`(3, Scheme_t.bgv) -> integer scheme.`

2022-08-17 16:35 UTC, ibarrond commented on Pyfhel/utils/Scheme_t.py
> +    """Integer encoding, used with encryptInt/decryptInt and encodeInt/decodeInt."""
used with encryptBGV/...

2022-08-17 16:35 UTC, ibarrond commented on examples/Demo_BGV.py
> +HelloWorld
Merge the two BGV demos into one, and name it `Demo_7_Integer_BGV.py` .

2022-08-17 16:35 UTC, ibarrond commented on examples/Demo_BGV2.py
> +"""
Merge with Demo_BGV

2022-08-17 17:39 UTC, ibarrond approved these changes

2022-10-04 22:47 UTC, ibarrond commented
A few things to change before merging:
1. Pyfhel==3.3.0 introduced a bunch of changes that conflict with this PR, and thus they need to be resolved.
2. The pull request still shows thousands of lines changed due to an issue with the newline. While this can be filtered out in Github, git is not that smart by itself. Remove all these unnecessary changes and rebase the entire pull request so that only the important changes are committed.
3. MacOS support is based on setting global environment variables, but this can be compiler-dependent and not controlled by Python. Review the approach to add compiler and linker directives only in the `pyproject.toml` file and avoid using environment variables.
4. Update Demo_7_BGV to Demo_9_BGV.
5. Add coverage tests to the new pieces of code.

2022-11-02 20:17 UTC, davidhassel commented
Any updates on this? We are trying test BGV, but have some issues with the installation (compilation errors in Pyfhel/Pyfhel.cpp when building 'Pyfhel.Pyfhel' extension) (e.g., `Pyfhel/Pyfhel.cpp:26069:64: error: cannot convert ‘std::vector<long long int>’ to ‘std::vector<long int>&’` when running `pip install .` However, not sure what stage this pull request is at?

@devharsh @ibarrond

2022-12-02 20:28 UTC, ibarrond commented
@davidhassel BGV is now implemented in the `dev` branch, building and testing correctly for Windows and Ubuntu. You can install it from there.

2022-12-02 20:32 UTC, ibarrond commented
@devharsh To avoid the full rewrite due to the newline issue you had, I mocked your commits in the `dev` branch and kept updating it there. Everything related to BGV now works in Windows/Linux, and I'm stuck with the installation in MacOs (testing it automatically in a fresh MacOs environment via Github Actions). If you have the time, let's move the discussion to #131 to solve the last missing issues.

Closing this branch!

2022-12-02 20:32 UTC, closed without merging

2022-12-02 20:39 UTC, devharsh commented
Sure, always happy to help!

Best,
Devharsh.

On Dec 2, 2022, at 3:32 PM, Alberto Ibarrondo ***@***.***> wrote:

﻿

@devharsh<https://github.com/devharsh> To avoid the full rewrite due to the newline issue you had, I mocked your commits in the dev branch and kept updating it there. Everything related to BGV now works in Windows/Linux, and I'm stuck with the installation in MacOs (testing it automatically in a fresh MacOs environment via Github Actions). If you have the time, let's move the discussion to #131<https://github.com/ibarrond/Pyfhel/issues/131> to solve the last missing issues.

Closing this branch!

—
Reply to this email directly, view it on GitHub<https://github.com/ibarrond/Pyfhel/pull/141#issuecomment-1335814457>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AATLUPTHRBSFFVS34LN7CCDWLJMFTANCNFSM56TKULGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>